# Generated by Django 2.2.7 on 2019-11-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_question_choice_five'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_five',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
