# Generated by Django 2.2.7 on 2019-11-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191111_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='questions1',
        ),
    ]
