# Generated by Django 2.2.7 on 2019-11-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_score_questions1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='answer1',
            new_name='answer',
        ),
    ]
