# Generated by Django 2.2.7 on 2019-11-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191111_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='answer',
            new_name='answer1',
        ),
        migrations.AddField(
            model_name='score',
            name='answer10',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='answer2',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='answer3',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='answer4',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='answer5',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='answer6',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='answer7',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='answer8',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='answer9',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
