# Generated by Django 2.2.7 on 2019-11-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191114_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='answer10',
        ),
        migrations.RemoveField(
            model_name='score',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='score',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='score',
            name='answer5',
        ),
        migrations.RemoveField(
            model_name='score',
            name='answer6',
        ),
        migrations.RemoveField(
            model_name='score',
            name='answer7',
        ),
        migrations.RemoveField(
            model_name='score',
            name='answer8',
        ),
        migrations.RemoveField(
            model_name='score',
            name='answer9',
        ),
    ]
