# Generated by Django 2.2.7 on 2019-11-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191114_1000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='Uscore',
        ),
    ]
